In [4]:
import numpy as np
from scipy.optimize import linprog

# Define the cost matrix
# Example cost matrix where rows represent sources and columns represent destinations
cost = np.array([
    [4, 8, 8],
    [2, 7, 6],
    [3, 4, 2]
])

# Flatten the cost matrix to use in linprog
c = cost.flatten()

# Define the supply array
supply = np.array([50, 40, 60])

# Define the demand array
demand = np.array([30, 70, 50])

# Create equality constraints matrix (A_eq) and right-hand side (b_eq)
A_eq = []
b_eq = []

# Supply constraints
for i in range(len(supply)):
    constraint = [0] * len(c)
    for j in range(len(demand)):
        constraint[i * len(demand) + j] = 1
    A_eq.append(constraint)
    b_eq.append(supply[i])

# Demand constraints
for j in range(len(demand)):
    constraint = [0] * len(c)
    for i in range(len(supply)):
        constraint[i * len(demand) + j] = 1
    A_eq.append(constraint)
    b_eq.append(demand[j])

# Solve the transportation problem using linprog
result = linprog(c, A_eq=A_eq, b_eq=b_eq, bounds=(0, None), method='highs')

# Reshape the result to the original cost matrix shape
result_matrix = result.x.reshape(cost.shape)

# Print the result
print('Optimal value (total cost):', result.fun)
print('Optimal transport plan:')
print(result_matrix)

Optimal value (total cost): 670.0
Optimal transport plan:
[[ 0. 50.  0.]
 [30. 10.  0.]
 [ 0. 10. 50.]]
